np.fromfile instead of np.fromstring is shorter and doesn't throw an assertion in python 2.7.
Original code, in python 2.7 was resulting in:

python train.py 
('opening:', '/home/dchichkov/n/wikitext-103-raw')
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    trX, vaX, teX = wiki3(path=args.data_file)
  File "/home/dchichkov/n/blocksparse/examples/lstm/utils.py", line 48, in wiki3
    tr_text = text_to_npy(os.path.join(path, "wiki.train.raw"))
  File "/home/dchichkov/n/blocksparse/examples/lstm/utils.py", line 42, in text_to_npy
    text = open(path).read(nbytes).encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 39: ordinal not in range(128)